version: '2'
services:
  db:
    image: mysql:5.7.23
    ports:
      - "3306:3306"
    # restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=myblog
  web:
    build: .
    command: bee run
    restart: always
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - .:/go/src/myblog
    links:
      - db
